version: "3"

services:
    app:
        image: cje3295/paraphernalia/basecoat:app
        volumes:
            - ${APP_DIRECTORY}:/var/www/basecoat
            - basecoat:/tmp

    nginx:
        image: cje3295/paraphernalia/basecoat:nginx
        volumes:
            - basecoat:/tmp
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app

    postgres:
        image: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - basecoat:/tmp
        expose:
            - "5432"

volumes:
    basecoat:
